version: '3.8'

services:




  # EvoDataAgent Core Service
  core-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evodata-core
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EVOLUTION_URL=${EVOLUTION_URL}
      - EVOLUTION_INSTANCE=${EVOLUTION_INSTANCE}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - MCP_SERVER_URL=http://mcp-simulator:8002/sse
      - WEBHOOK_SERVER_PORT=5000
      - FILE_SERVER_PORT=8001
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    ports:
      - "5000:5000"
      - "8001:8001"
    
    volumes:
      - ./logs:/app/logs
      - ./exports:/app/exports
      - ./temp:/app/temp
    
    networks:
      - mct-network
    restart: unless-stopped

networks:
  mct-network:
    name: mct-network
    driver: bridge
